spring.application.name=siacredit
# 1. Cambiamos el puerto a 8081 para esquivar al Tomcat de XAMPP
server.port=8081

# 2. Conexión a MySQL ACTUALIZADA (Puerto 3309 según tu imagen)
spring.datasource.url=jdbc:mysql://localhost:3309/siacredit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# IMPORTANTE: Asegúrate de que el usuario y clave sean los de tu base de datos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Permitir subir recibos y PDFs de hasta 10 Megabytes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB